github.com:
    users:
        usertype46-collab:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: usertype46-collab
